-- ==========================================================
-- RESEARCH IT DATABASE SCHEMA & MOCK DATA SEED
-- Paste this script in your Supabase SQL Editor to initialize tables.
-- ==========================================================

-- 1. DIRECTORY / USER PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    email text DEFAULT '',
    name text NOT NULL,
    role text NOT NULL CHECK (role IN ('student', 'researcher', 'mentor', 'admin')),
    institution text NOT NULL,
    domain text NOT NULL,
    verified boolean DEFAULT false,
    connections integer DEFAULT 0,
    skills text[] DEFAULT '{}'::text[],
    interests text DEFAULT '',
    linkedin_url text DEFAULT '',
    avatar_url text DEFAULT '',
    streak integer DEFAULT 5,
    credits integer DEFAULT 120,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Ensure columns exist if the table was already created
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS email text DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS profiles_user_id_idx ON public.profiles(user_id);


-- 2. PROJECT SHOWCASES TABLE
CREATE TABLE IF NOT EXISTS public.showcases (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    domain text NOT NULL,
    description text NOT NULL,
    mentor text NOT NULL,
    institution text NOT NULL,
    publisher text DEFAULT '',
    paper_link text DEFAULT '',
    demo_link text DEFAULT '',
    likes integer DEFAULT 0,
    liked boolean DEFAULT false,
    team jsonb DEFAULT '[]'::jsonb,
    approved boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. RESEARCH OPPORTUNITIES TABLE
CREATE TABLE IF NOT EXISTS public.opportunities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    researcher text NOT NULL,
    lab text NOT NULL,
    domain text NOT NULL,
    skills text NOT NULL,
    duration text NOT NULL,
    slots integer NOT NULL,
    applied boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. OPPORTUNITY APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.opportunity_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id bigint REFERENCES public.opportunities(id) ON DELETE CASCADE,
    student_name text NOT NULL,
    student_college text NOT NULL,
    student_role text NOT NULL,
    project_title text NOT NULL,
    status text NOT NULL CHECK (status IN ('Pending', 'Approved', 'Declined')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. COMMUNITY HUB FEED POSTS TABLE
CREATE TABLE IF NOT EXISTS public.feed (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author text NOT NULL,
    role text NOT NULL,
    time text NOT NULL,
    body text NOT NULL,
    likes integer DEFAULT 0,
    liked boolean DEFAULT false,
    paper_link text DEFAULT '',
    channel text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. MENTORSHIP SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.mentorship_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student text NOT NULL,
    topic text NOT NULL,
    date text NOT NULL,
    platform text NOT NULL,
    status text NOT NULL CHECK (status IN ('Scheduled', 'Completed', 'Cancelled')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. PENDING VERIFICATIONS QUEUE TABLE
CREATE TABLE IF NOT EXISTS public.verifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('Researcher', 'Mentor')),
    affiliation text NOT NULL,
    bio text NOT NULL,
    status text DEFAULT 'Pending' NOT NULL CHECK (status IN ('Pending', 'Approved', 'Declined')),
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. LEARNING CENTER COURSES TABLE
CREATE TABLE IF NOT EXISTS public.courses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category text NOT NULL,
    title text NOT NULL,
    duration text NOT NULL,
    modules integer NOT NULL,
    progress integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- ==========================================================
-- INITIAL DATA SEEDING COMMANDS
-- ==========================================================

-- Clean existing seed data to prevent duplication
TRUNCATE public.profiles, public.showcases, public.opportunities, public.opportunity_applications, public.feed, public.mentorship_sessions, public.verifications, public.courses RESTART IDENTITY CASCADE;

-- A. Seed Profiles (Users, Researchers, Mentors, Admins)
INSERT INTO public.profiles (name, role, institution, domain, verified, connections, skills, interests, linkedin_url, avatar_url, streak, credits) VALUES
('Dr. Samir Kalra', 'researcher', 'AIIMS Delhi', 'AI & Healthcare', true, 184, ARRAY['Computer Vision', 'Radiology', 'Deep Learning'], 'AI Clinical Diagnostics', 'https://linkedin.com/in/samir-kalra-mock', '', 8, 320),
('Prof. Ananya Sen', 'researcher', 'IIT Kharagpur', 'Biotechnology', true, 232, ARRAY['Genetics', 'CRISPR', 'Biochemical Lab'], 'CRISPR Biofuel Strains', 'https://linkedin.com/in/ananya-sen-mock', '', 12, 450),
('Dr. Kabir Mehta', 'mentor', 'NIMHANS Bangalore', 'Psychology', true, 92, ARRAY['Cognitive Therapy', 'Clinical Studies'], 'Cognitive Burnout Studies', 'https://linkedin.com/in/kabir-mehta-mock', '', 4, 180),
('Rahul Sharma', 'mentor', 'Biogenics India Pvt Ltd', 'Biomedical', false, 45, ARRAY['Medical Devices', 'FDA Approvals'], 'MedTech Regulation', 'https://linkedin.com/in/rahul-sharma-mock', '', 0, 50),
('Aarav Gupta', 'student', 'IIT Delhi', 'AI & Deep Learning', false, 24, ARRAY['Python', 'PyTorch', 'Data Structures'], 'Computer Vision', '', '', 5, 120),
('Meera Nair', 'student', 'BITS Pilani', 'Biotechnology & Genetics', false, 18, ARRAY['R', 'Bioinformatics', 'Gel Electrophoresis'], 'Biofuel Pathways', '', '', 3, 95),
('Administrator', 'admin', 'BioLabs HQ', 'System Control', true, 500, ARRAY['Database Administration', 'System Operations'], 'Security protocols', '', '', 10, 1000);

-- B. Seed Project Showcases
INSERT INTO public.showcases (title, domain, description, mentor, institution, publisher, paper_link, demo_link, likes, liked, team, approved) VALUES
(
    'GenAI Radiology Assistant (RadiolAI)',
    'Medical',
    'An AI-powered diagnostic tool capable of identifying 14 types of lung anomalies from chest X-rays with 94.2% accuracy. Developed by a student research group during a 6-month lab residency under Dr. Samir Kalra.',
    'Dr. Samir Kalra',
    'AIIMS Delhi',
    'Nature Machine Intelligence',
    'https://arxiv.org/abs/2606.12345',
    'https://github.com/research-it/radiolai-demo',
    124,
    false,
    '[{"name": "Aarav Gupta", "role": "AI Engineer", "avatar": "AG"}, {"name": "Priya Rao", "role": "Dataset Curator", "avatar": "PR"}, {"name": "Karan Sharma", "role": "Fullstack Dev", "avatar": "KS"}]'::jsonb,
    true
),
(
    'CRISPR-Modified Biofuel Yeast Strains',
    'Biotechnology',
    'Engineered yeast strains using CRISPR-Cas9 pathways to increase ethanol production efficiency from agricultural biomass by 18% under Prof. Ananya Sen.',
    'Prof. Ananya Sen',
    'IIT Kharagpur',
    'Biotechnology & Biofuels Journal',
    'https://doi.org/10.1186/s13068-026-mock',
    'https://github.com/research-it/crispr-biofuel',
    98,
    false,
    '[{"name": "Rohan Verma", "role": "Lab Lead", "avatar": "RV"}, {"name": "Sneha Patel", "role": "Gene Analyst", "avatar": "SP"}]'::jsonb,
    true
),
(
    'TheraBot: Cognitive Behavioral Therapy Agent',
    'Psychology',
    'An interactive mental health companion utilizing specialized CBT rulesets to monitor fatigue metrics and deliver personalized guidance under Dr. Kabir Mehta.',
    'Dr. Kabir Mehta',
    'NIMHANS Bangalore',
    'JMIR Mental Health',
    'https://mental.jmir.org/2026/mock',
    'https://github.com/research-it/therabot-cbt',
    85,
    false,
    '[{"name": "Meera Nair", "role": "Cognitive Dev", "avatar": "MN"}, {"name": "Kabir Roy", "role": "NLP Engineer", "avatar": "KR"}]'::jsonb,
    true
);

-- C. Seed Research Opportunities
INSERT INTO public.opportunities (title, researcher, lab, domain, skills, duration, slots, applied) VALUES
('GenAI for Radiology Diagnosis', 'Dr. Samir Kalra', 'Clinical AI Diagnostics Lab', 'AI', 'PyTorch, CNNs, Python', '6 Months', 2, false),
('CRISPR Pathway Engineering in Biofuels', 'Prof. Ananya Sen', 'Molecular Genetics Center', 'Biotechnology', 'Genomics, Gel Electrophoresis', '1 Year', 1, false),
('Cognitive Fatigue & Remote Work Productivity', 'Dr. Kabir Mehta', 'Cognitive Sciences Division', 'Psychology', 'R, SPSS, Survey Design', '3 Months', 4, false),
('Prosthetic Grip Control via EMG Decoding', 'Prof. Rajesh Kumar', 'Bionics & Robotics Laboratory', 'Biomedical', 'C++, Signal Processing, MATLAB', '8 Months', 2, false),
('Urban Air Quality & Respiratory Admissions', 'Dr. Priya Patel', 'School of Public Health', 'Public Health', 'GIS Mapping, Epidemiology, R', '4 Months', 3, false);

-- D. Seed Applications
INSERT INTO public.opportunity_applications (opportunity_id, student_name, student_college, student_role, project_title, status) VALUES
(1, 'Aarav Gupta', 'IIT Delhi', 'Student Researcher', 'GenAI for Radiology Diagnosis', 'Pending'),
(2, 'Meera Nair', 'BITS Pilani', 'Lab Assistant', 'CRISPR Pathway Engineering in Biofuels', 'Approved'),
(3, 'Aditya Verma', 'Delhi University', 'Data Analyst', 'Cognitive Fatigue Study', 'Pending');

-- E. Seed Community Feed
INSERT INTO public.feed (author, role, time, body, likes, liked, paper_link, channel) VALUES
('Dr. Samir Kalra', 'researcher', '2 hours ago', 'Excited to share our team''s latest preprint paper on ''Multimodal Transformer Architectures for Lung Nodule Segments'' in Nature Machine Intelligence. Looking for student collaborators with strong PyTorch experience to extend this to cardiovascular MRI scans! Drop an application in our Opportunities section.', 42, false, 'arxiv.org/abs/2606.12345', 'AI in Healthcare'),
('Dr. Kabir Mehta', 'mentor', '1 day ago', 'Had an amazing mentoring session with 15 undergraduate students yesterday on ''How to formulate a scientific hypothesis''. For those who missed it, I have uploaded the slide deck and sample outline templates in the resource channel. Next session scheduled for clinical case designs next Saturday!', 29, false, '', 'Neuroscience Hub'),
('Siddharth Verma', 'student', '3 hours ago', 'Great news for IIT Delhi folks! Nvidia is visiting campus next week for AI researcher recruitment. If you need prep materials or references, reach out to me as your College Chapter Lead. Let''s make our campus proud!', 15, false, '', 'IIT Delhi Chapter'),
('Meera Nair', 'student', '5 hours ago', 'Biotech lab material sourcing updates: We''ve received fresh stock of CRISPR enzyme kits. If any project teams at BITS Pilani need authorization or material resources, contact me directly. Let''s build something bio-innovative!', 8, false, '', 'BITS Pilani Chapter'),
('Dr. Rohan Malhotra', 'researcher', '1 day ago', 'AIIMS Delhi Chapter is hosting a clinical data hackathon next weekend. Research opportunities with clinicians will be open for top-performing students. Contact me if you have any questions or require clinical datasets for validation.', 31, false, '', 'AIIMS Delhi Chapter'),
('Anjali Deshmukh', 'student', '2 days ago', 'Undergraduate cognitive surveys templates are now hosted in the NIMHANS Chapter repository. Students researching remote work burnout can access this dataset by clicking the resource links. Ping me for access credentials.', 12, false, '', 'NIMHANS Chapter');

-- F. Seed Mentorship Sessions
INSERT INTO public.mentorship_sessions (student, topic, date, platform, status) VALUES
('Riya Sen', 'Biotech Thesis Structure Feedback', 'June 20, 2026 at 4:00 PM', 'Zoom', 'Scheduled'),
('Kunal Ghosh', 'AI/ML Career Guidance Session', 'June 22, 2026 at 11:00 AM', 'Google Meet', 'Scheduled');

-- G. Seed Verifications
INSERT INTO public.verifications (name, type, affiliation, bio, status) VALUES
('Dr. Vikram Seth', 'Researcher', 'IISc Bangalore', 'Genomics Research Fellow', 'Pending'),
('Sneha Nair', 'Mentor', 'MedTech Innovations', 'Regulatory Specialist', 'Pending');

-- H. Seed Courses
INSERT INTO public.courses (category, title, duration, modules, progress) VALUES
('Methodology', 'Foundations of Research Methodology', '4 weeks', 8, 80),
('Statistics', 'Biostatistics and Data Wrangling in R', '6 weeks', 12, 25),
('Scientific Writing', 'Structuring High-Impact Journal Papers', '3 weeks', 6, 0),
('Academic Publishing', 'Navigating Peer Review & Journal Selection', '2 weeks', 4, 0);

-- Enable Realtime for community feed table
ALTER TABLE public.feed REPLICA IDENTITY FULL;
ALTER PUBLICATION supabase_realtime ADD TABLE public.feed;

-- ==========================================================
-- ROW LEVEL SECURITY POLICIES
-- Required for the anon key to read/write from the browser.
-- Run this AFTER creating tables (or re-run the full script).
-- ==========================================================

-- PROFILES
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "profiles_select_all" ON public.profiles;
DROP POLICY IF EXISTS "profiles_insert_all" ON public.profiles;
DROP POLICY IF EXISTS "profiles_update_all" ON public.profiles;
DROP POLICY IF EXISTS "profiles_delete_all" ON public.profiles;
CREATE POLICY "profiles_select_all" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_insert_all" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "profiles_update_all" ON public.profiles FOR UPDATE USING (true);
CREATE POLICY "profiles_delete_all" ON public.profiles FOR DELETE USING (true);

-- SHOWCASES
ALTER TABLE public.showcases ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "showcases_select_all" ON public.showcases;
DROP POLICY IF EXISTS "showcases_insert_all" ON public.showcases;
DROP POLICY IF EXISTS "showcases_update_all" ON public.showcases;
DROP POLICY IF EXISTS "showcases_delete_all" ON public.showcases;
CREATE POLICY "showcases_select_all" ON public.showcases FOR SELECT USING (true);
CREATE POLICY "showcases_insert_all" ON public.showcases FOR INSERT WITH CHECK (true);
CREATE POLICY "showcases_update_all" ON public.showcases FOR UPDATE USING (true);
CREATE POLICY "showcases_delete_all" ON public.showcases FOR DELETE USING (true);

-- OPPORTUNITIES
ALTER TABLE public.opportunities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "opportunities_select_all" ON public.opportunities;
DROP POLICY IF EXISTS "opportunities_insert_all" ON public.opportunities;
DROP POLICY IF EXISTS "opportunities_update_all" ON public.opportunities;
DROP POLICY IF EXISTS "opportunities_delete_all" ON public.opportunities;
CREATE POLICY "opportunities_select_all" ON public.opportunities FOR SELECT USING (true);
CREATE POLICY "opportunities_insert_all" ON public.opportunities FOR INSERT WITH CHECK (true);
CREATE POLICY "opportunities_update_all" ON public.opportunities FOR UPDATE USING (true);
CREATE POLICY "opportunities_delete_all" ON public.opportunities FOR DELETE USING (true);

-- OPPORTUNITY APPLICATIONS
ALTER TABLE public.opportunity_applications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "applications_select_all" ON public.opportunity_applications;
DROP POLICY IF EXISTS "applications_insert_all" ON public.opportunity_applications;
DROP POLICY IF EXISTS "applications_update_all" ON public.opportunity_applications;
DROP POLICY IF EXISTS "applications_delete_all" ON public.opportunity_applications;
CREATE POLICY "applications_select_all" ON public.opportunity_applications FOR SELECT USING (true);
CREATE POLICY "applications_insert_all" ON public.opportunity_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "applications_update_all" ON public.opportunity_applications FOR UPDATE USING (true);
CREATE POLICY "applications_delete_all" ON public.opportunity_applications FOR DELETE USING (true);

-- FEED
ALTER TABLE public.feed ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "feed_select_all" ON public.feed;
DROP POLICY IF EXISTS "feed_insert_all" ON public.feed;
DROP POLICY IF EXISTS "feed_update_all" ON public.feed;
DROP POLICY IF EXISTS "feed_delete_all" ON public.feed;
CREATE POLICY "feed_select_all" ON public.feed FOR SELECT USING (true);
CREATE POLICY "feed_insert_all" ON public.feed FOR INSERT WITH CHECK (true);
CREATE POLICY "feed_update_all" ON public.feed FOR UPDATE USING (true);
CREATE POLICY "feed_delete_all" ON public.feed FOR DELETE USING (true);

-- MENTORSHIP SESSIONS
ALTER TABLE public.mentorship_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "sessions_select_all" ON public.mentorship_sessions;
DROP POLICY IF EXISTS "sessions_insert_all" ON public.mentorship_sessions;
DROP POLICY IF EXISTS "sessions_update_all" ON public.mentorship_sessions;
DROP POLICY IF EXISTS "sessions_delete_all" ON public.mentorship_sessions;
CREATE POLICY "sessions_select_all" ON public.mentorship_sessions FOR SELECT USING (true);
CREATE POLICY "sessions_insert_all" ON public.mentorship_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "sessions_update_all" ON public.mentorship_sessions FOR UPDATE USING (true);
CREATE POLICY "sessions_delete_all" ON public.mentorship_sessions FOR DELETE USING (true);

-- VERIFICATIONS
ALTER TABLE public.verifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "verif_select_all" ON public.verifications;
DROP POLICY IF EXISTS "verif_insert_all" ON public.verifications;
DROP POLICY IF EXISTS "verif_update_all" ON public.verifications;
DROP POLICY IF EXISTS "verif_delete_all" ON public.verifications;
CREATE POLICY "verif_select_all" ON public.verifications FOR SELECT USING (true);
CREATE POLICY "verif_insert_all" ON public.verifications FOR INSERT WITH CHECK (true);
CREATE POLICY "verif_update_all" ON public.verifications FOR UPDATE USING (true);
CREATE POLICY "verif_delete_all" ON public.verifications FOR DELETE USING (true);

-- COURSES
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "courses_select_all" ON public.courses;
DROP POLICY IF EXISTS "courses_insert_all" ON public.courses;
DROP POLICY IF EXISTS "courses_update_all" ON public.courses;
DROP POLICY IF EXISTS "courses_delete_all" ON public.courses;
CREATE POLICY "courses_select_all" ON public.courses FOR SELECT USING (true);
CREATE POLICY "courses_insert_all" ON public.courses FOR INSERT WITH CHECK (true);
CREATE POLICY "courses_update_all" ON public.courses FOR UPDATE USING (true);
CREATE POLICY "courses_delete_all" ON public.courses FOR DELETE USING (true);


-- ==========================================================
-- RESEND EMAIL INTEGRATION (SIGNUP & LOGIN NOTIFICATIONS)
-- ==========================================================

-- Enable pg_net extension to support asynchronous HTTP requests
CREATE EXTENSION IF NOT EXISTS pg_net;

-- Create logins table
CREATE TABLE IF NOT EXISTS public.logins (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    email text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS on logins
ALTER TABLE public.logins ENABLE ROW LEVEL SECURITY;

-- Allow users to insert their own login events
DROP POLICY IF EXISTS "Allow authenticated users to insert their own logins" ON public.logins;
CREATE POLICY "Allow authenticated users to insert their own logins" ON public.logins
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 1. Trigger function for auth.users (Welcome Email on Sign Up)
CREATE OR REPLACE FUNCTION public.send_welcome_email_on_signup()
RETURNS TRIGGER AS $$
DECLARE
    user_name text;
    user_role text;
BEGIN
    user_name := COALESCE(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1));
    user_role := COALESCE(new.raw_user_meta_data->>'role', 'student');

    PERFORM net.http_post(
        url := 'https://api.resend.com/emails',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer re_JnCFepYU_EMuRuxnrJbbFJv8V9TBGxZRL'
        ),
        body := jsonb_build_object(
            'from', 'BioLabs Research <no-reply@biolabsresearch-healix.com>',
            'to', jsonb_build_array(new.email),
            'subject', 'Welcome to BioLabs Research!',
            'html', '
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h2 style="color: #6d28d9; margin: 0;">BioLabs Research</h2>
                    <p style="color: #64748b; font-size: 14px; margin: 5px 0 0 0;">India''s Research Collaboration & Mentorship Platform</p>
                </div>
                <div style="line-height: 1.6; color: #334155; font-size: 15px;">
                    <p>Dear ' || user_name || ',</p>
                    <p>Welcome to <strong>BioLabs Research</strong>! We are thrilled to have you join our scientific community.</p>
                    <p>Your account has been registered successfully as a <strong>' || initcap(user_role) || '</strong>.</p>
                    <p>Here are a few things you can do to get started:</p>
                    <ul>
                        <li>Complete your profile with your domains and skills</li>
                        <li>Explore ongoing research projects and opportunity listings</li>
                        <li>Connect with verified mentors and clinicians</li>
                        <li>Share your own research updates in the Community Feed</li>
                    </ul>
                    <p>If you have any questions or need support, feel free to contact us at support@biolabsresearch-healix.com.</p>
                </div>
                <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                <div style="text-align: center; color: #94a3b8; font-size: 12px;">
                    <p>&copy; 2026 BioLabs Research. All rights reserved.</p>
                </div>
            </div>'
        )
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger on auth.users
DROP TRIGGER IF EXISTS tr_auth_users_welcome_email ON auth.users;
CREATE TRIGGER tr_auth_users_welcome_email
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.send_welcome_email_on_signup();

-- 2. Trigger function for logins (Login Notification)
CREATE OR REPLACE FUNCTION public.send_login_email()
RETURNS TRIGGER AS $$
BEGIN
    PERFORM net.http_post(
        url := 'https://api.resend.com/emails',
        headers := jsonb_build_object(
            'Content-Type', 'application/json',
            'Authorization', 'Bearer re_JnCFepYU_EMuRuxnrJbbFJv8V9TBGxZRL'
        ),
        body := jsonb_build_object(
            'from', 'BioLabs Research <no-reply@biolabsresearch-healix.com>',
            'to', jsonb_build_array(new.email),
            'subject', 'New Login to BioLabs Research',
            'html', '
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 8px; background-color: #ffffff;">
                <div style="text-align: center; margin-bottom: 20px;">
                    <h2 style="color: #6d28d9; margin: 0;">BioLabs Research</h2>
                </div>
                <div style="line-height: 1.6; color: #334155; font-size: 15px;">
                    <p>Hello ' || new.name || ',</p>
                    <p>We detected a new login to your BioLabs Research account on <strong>' || to_char(new.created_at AT TIME ZONE 'Asia/Kolkata', 'DD Mon YYYY, HH24:MI:SS') || ' (IST)</strong>.</p>
                    <p>If this was you, no action is needed. If you did not log in, please reset your password immediately to secure your account.</p>
                </div>
                <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;">
                <div style="text-align: center; color: #94a3b8; font-size: 12px;">
                    <p>&copy; 2026 BioLabs Research. All rights reserved.</p>
                </div>
            </div>'
        )
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger on logins
DROP TRIGGER IF EXISTS tr_logins_notification_email ON public.logins;
CREATE TRIGGER tr_logins_notification_email
    AFTER INSERT ON public.logins
    FOR EACH ROW EXECUTE FUNCTION public.send_login_email();


-- 3. Trigger to auto-confirm all signups in auth.users (prevents email link verify blocks)
CREATE OR REPLACE FUNCTION public.auto_confirm_new_users()
RETURNS TRIGGER AS $$
BEGIN
    NEW.email_confirmed_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS tr_auto_confirm_new_users ON auth.users;
CREATE TRIGGER tr_auto_confirm_new_users
    BEFORE INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.auto_confirm_new_users();
